FROM ubuntu
RUN apt-get update &&  apt-get install openssh-server -y &&  apt-get install openssh-client -y
WORKDIR /root/.ssh
RUN service ssh start
RUN chmod 700 /root/.ssh && chown root:root /root/.ssh
COPY acess_public/id_rsa.pub .
RUN chmod 644 id_rsa.pub && chown root:root id_rsa.pub
RUN cp id_rsa.pub authorized_keys
RUN chmod 644 authorized_keys && chown root:root authorized_keys
WORKDIR /home/service
COPY acess_public/service .
EXPOSE 22
CMD ["/usr/lib/systemd/systemd"]