---
 - name: 'install all list'
   apt:
     name: "{{ item }}"
     state: latest
   loop:
     - python3
     - python3-pip
     - curl
     - nano
      
 - name: 'install pip package' 
   pip: 
     name: ['Flask']
     state: latest
 
 - name: 'start service'
   shell: cd /home/service && nohup python3 Main.py & 

 - name: 'status service' 
   shell: export PORT_PY='8080'&& cd /home/service && ./status_service.sh
   register: dzinfo_output
   
 - debug:
     var: dzinfo_output.stdout_lines
  
 - name: 'show msh'
   shell: "echo my name is {{ item }}"
   register: my_relatory

 - name: 'show my relatory'
   debug:
      var: my_relatory
 
