pipeline {

    agent any
    stages {
        stage('Run container'){
            steps{
                sh 'docker run -dti -p 8090:8080 --name ubuntu_python ubuntu_python'
            }
        }
       stage('Test app'){
            steps{
                sh 'curl localhost:8090'
            }
        }

    
        
    }
}