pipeline {

    agent any
    stages {
        stage('Run container'){
            steps{
                sh 'docker run -dti -p 8080:8080 --name ubuntu_python ubuntu_python'
            }
        }
       stage('Test app'){
            steps{
                sh 'docker exec ubuntu_python curl localhost:8080'
            }
        }

    
        
    }
}
