pipeline {
    agent any
    stages {
        stage ('Git connect'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/joaobilegra/tema13_docker.git']]])
            }
        }

        stage ('Build application') {
            steps {
                sh 'docker build -t ubuntu_python .'
               
            }
        }
    }
}